### ISSUE TITLE
Buffer size

### ISSUE THREAD

**Issue by sbonaime** [scottchiefbaker/Arduino-SimpleSyslog#1]
Hi,

I want to use Arduino-SimpleSyslog but I had a problem. 
I want to send the following string
````
{"capteur":"'testss24:0A:C4:EA:48:08'","datetime":"'2022-05-01 00:04:11.0'","lat":0,"lon":0,"elv_m":0,"alt_m":-17,"fix":0,"car":0,"hacc_mm":4294967295,"vacc_mm":3750000128,"numsv":0}
````
which I can see in the Serial Monior. 

But the packet received by syslogd is only
````
2024-09-26T09:09:19.205931+02:00 Serveur-syslog RTK-DZIANI: {"capteur":"'testss24:0A:C4:EA:48:08'","datetime":"'2022-05-01 00:02:11.0'","lat":0,"lon":0,"elv_m":0,"alt_m":-17,"fix":0,"car"
````
And I found what is the problem. 
https://github.com/scottchiefbaker/Arduino-SimpleSyslog/blob/0b79d145ae465424f808189c437f8d72eb26fb3a/SimpleSyslog.h#L58
https://github.com/scottchiefbaker/Arduino-SimpleSyslog/blob/0b79d145ae465424f808189c437f8d72eb26fb3a/SimpleSyslog.h#L59

This buffer is only 128 bytes long. If I increase it to 256, I have no problem sending my message. 
Maybe we can have another parameter for SimpleSyslog which could be max_buffer_size with a default of 256. 
What do you think ? 
I can try to do a PR

**Comment by sbonaime** [comment]
And by the way, why MAX_PACKET_SIZE is equal to char buf[128] +  128 ? Is it the overhead of the packet ? 
Then maybe we can set 
MAX_PACKET_SIZE = max_buffer_size + 128

**Comment by sbonaime** [comment]
https://github.com/scottchiefbaker/Arduino-SimpleSyslog/pull/2

**Comment by scottchiefbaker** [comment]
This looks decent to me. I don't think we need `_max_buffer_size + OVERHEAD_PACKET_SIZE` though. I think if we just up the tweak the `MAX_PACKET_SIZE` variable the fashion you laid out we'll be good, and it will be simpler. If you update this PR as described I will land the code.

**Comment by scottchiefbaker** [comment]
Thanks for the contribution!
